/*// See https://aka.ms/new-console-template for more information

// I'm working in .NET 6.0, so I don't have the System, Using, or other formatting statements included. I can use another version if you'd like. 
*//* Prompt #1 - Create a simple console application and store your name, age (should take decimal), address in a string variable and print them back on console. 
 * Prompt the user to each time enter name, age and address.*//*
Console.WriteLine("Hello, thank you for using our services today. Please tell us your first name.");
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type. I used a lot of the autogenerated error handling recommendations. Sorry.
string studentFirstName = Console.ReadLine();
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
Console.WriteLine("Excellent, thank you. Please enter your last name.");
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
string studentLastName = Console.ReadLine();
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
Console.WriteLine("Great! For our own records, how old are you?");
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
string studentAge = Console.ReadLine();
Convert.ToDecimal(studentAge);
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
Console.WriteLine("Thank you. Finally, so we can send you pertinent correspondence (if any), what is your mailing address?");
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
string studentAddress = Console.ReadLine();
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.

Console.WriteLine($"Alright, we've recorded that you are {studentFirstName} {studentLastName}, {studentAge} years old, living at {studentAddress}. Thanks!");


// Prompt #2 - Create a simple console application and declare basic datatypes like int, float, decimal, double and print their min and max values.
int numOne = 23;
float numTwo = 9.346f;
double numThree = 9.9;
decimal numFour = 48.88m;

int[] numArray = { numOne, Convert.ToInt32(numTwo), Convert.ToInt32(numThree), Convert.ToInt32(numFour) };

int maxValue = numArray.Max();
int minValue = numArray.Min();

Console.WriteLine($"Awesome. The minimum value in the set was {minValue} and the maximum value was {maxValue}");*/

int firstNumber = 20;
decimal secondNumber = 10.5m;

//Console.WriteLine($"The sum of {firstNumber} and {secondNumber} is {firstNumber + secondNumber}.");
Console.WriteLine(firstNumber);